name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust for Xtensa
      uses: esp-rs/xtensa-toolchain@v1.5
      with:
        default: true
        version: "1.80.0"
        ldproxy: true
    - uses: actions/checkout@v4
      with:
        path: ws2812-esp32-rmt-driver
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ws2812-esp32-rmt-driver/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: |
        cargo build
        cargo build --all-features
        cargo build --no-default-features --features=alloc
        cargo build --no-default-features --features=alloc,smart-leds-trait,embedded-graphics-core
        cargo build --no-default-features
        cargo build --no-default-features --features=smart-leds-trait,embedded-graphics-core
      working-directory: ./ws2812-esp32-rmt-driver
    - name: Build examples
      run: cargo build --examples --all-features
      working-directory: ./ws2812-esp32-rmt-driver
    - name: Test
      run: |
        cargo +stable test --target x86_64-unknown-linux-gnu --lib
        cargo +stable test --target x86_64-unknown-linux-gnu --lib --all-features
        cargo +stable test --target x86_64-unknown-linux-gnu --lib --no-default-features --features std,smart-leds-trait
        cargo +stable test --target x86_64-unknown-linux-gnu --lib --no-default-features --features std,embedded-graphics-core
        cargo +stable test --target x86_64-unknown-linux-gnu --doc --all-features
      working-directory: ./ws2812-esp32-rmt-driver
    - name: Publish (Dry run)
      run: cargo +stable publish --target x86_64-unknown-linux-gnu --dry-run
      working-directory: ./ws2812-esp32-rmt-driver
